accounts/urls.py
from django.urls import include, re_path


from .views import (
    login_view,
    register_view,
    logout_view,
    select_user,
    change_password_view,
    decrypt_password_view
)

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^decrypt-password/$', decrypt_password_view, name='decrypt_password'),
]

giftsite/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('giftweb.urls', namespace='giftweb')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

giftweb/urls.py
from django.urls import path
from .views import *

app_name = 'giftweb'

urlpatterns = [
    path('', home, name='home'),
    path('premium_home', premium_home, name='premium_home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('blogs/', blog_list, name='blog_list'),
    path('cart/', cart, name='cart'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),

    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('make_payment/<str:model_name>/<int:product_id>/', make_payment, name='make_payment'),
    path('payment_success/', payment_success, name='payment_success'),
    path('premium_product/<int:pk>/', PremiumProductDetailView.as_view(), name='premium_product_detail'),
    
    # Add the following URL for payment history
    path('payment_history/', payment_history, name='payment_history'),
]

giftweb/models.py

from django.db import models
from ckeditor.fields import RichTextField
from datetime import datetime

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    countdown_time = models.DurationField()
    image = models.ImageField(upload_to='product_images/')
    timestamp = models.DateTimeField(auto_now_add=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name


class PremiumProduct(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    countdown_time = models.DurationField()
    image = models.ImageField(upload_to='product_images/')
    extra_feature = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


    def __str__(self):
        return self.name


class Payment(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('COMPLETE', 'Complete')
    ]

    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    premium_product = models.ForeignKey(PremiumProduct, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2)

    proof_of_pay = models.ImageField(upload_to='photos/', null=True, blank=True)
    gift_card_type = models.CharField(choices=[('apple', 'Apple Card'), ('amazon', 'Amazon Card'), ('steam', 'Steam Card'), ('xbox', 'Xbox Card')], max_length=10)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='PENDING')
    date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    
    def mark_as_complete(self):
        self.completed = True
        self.save()
    def __str__(self):
        return f"{self.user} paid {self.amount} for {self.product}"

    class Meta:
        verbose_name = "Manage Deposit/Payment"
        verbose_name_plural = "Manage Deposit/Payment"


class CartItem(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    premium_product = models.ForeignKey(PremiumProduct, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Cart item {self.id} - User: {self.user.username}, Product: {self.product.name}"

class Blog(models.Model):
    topic = models.CharField(max_length=255)
    image = models.ImageField(upload_to='blog_images/')
    body = RichTextField()
    date = models.DateField()
    read_more = models.CharField(max_length=255, default='GiftCard')

    def __str__(self):
        return self.topic

class Contactor(models.Model):
  name = models.CharField(max_length=200)
  email = models.CharField(max_length=100)
  subject = models.CharField(max_length=200, blank=True)

  message = models.TextField(blank=True)
  contact_date = models.DateTimeField(default=datetime.now, blank=True)
  user_id = models.IntegerField(blank=True)


  def __str__(self):
    return self.name

giftweb/forms.py
from django import forms
from .models import Payment

class PaymentForm(forms.ModelForm):
    gift_card_type = forms.ChoiceField(choices=[('apple', 'Apple Card'), ('amazon', 'Amazon Card'), ('steam', 'Steam Card'), ('xbox', 'Xbox Card')])

    class Meta:
        model = Payment
        fields = ['amount', 'proof_of_pay', 'gift_card_type']

giftweb/views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import *
from .forms import PaymentForm
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from datetime import timedelta
from django.core.paginator import Paginator
from django.contrib import messages

class ProductDetailView(DetailView):
    model = Product
    template_name = 'giftweb/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()

        # Calculate the remaining time for the countdown
        remaining_time = product.countdown_time - (timezone.now() - product.timestamp)
        days = remaining_time.days
        hours, remainder = divmod(remaining_time.seconds, 3600)
        minutes, seconds = divmod(remainder, 60)

        context['days'] = days
        context['hours'] = hours
        context['minutes'] = minutes
        context['seconds'] = seconds

        # Calculate the discounted price if a discount is applicable
        if product.discount:
            discounted_price = product.price - product.discount
            context['discounted_price'] = discounted_price

        return context

def home(request):
    products = Product.objects.all()

    # Calculate the remaining time for each product
    current_time = timezone.now()
    for product in products:
        remaining_time = product.countdown_time - (current_time - product.timestamp)
        days = remaining_time.days
        hours, remainder = divmod(remaining_time.seconds, 3600)
        minutes, seconds = divmod(remainder, 60)

        product.remaining_days = days
        product.remaining_hours = hours
        product.remaining_minutes = minutes
        product.remaining_seconds = seconds

        # Calculate the discounted price if a discount is applicable
        if product.discount:
            discounted_price = product.price - (product.price * product.discount / 100)
            product.discounted_price = discounted_price

    return render(request, 'giftweb/index.html', {'products': products})

def premium_home(request):
    products = PremiumProduct.objects.all()

    # Calculate the remaining time for each product
    current_time = timezone.now()
    for product in products:
        remaining_time = product.countdown_time - (current_time - product.timestamp)
        days = remaining_time.days
        hours, remainder = divmod(remaining_time.seconds, 3600)
        minutes, seconds = divmod(remainder, 60)

        product.remaining_days = days
        product.remaining_hours = hours
        product.remaining_minutes = minutes
        product.remaining_seconds = seconds

        # Calculate the discounted price if a discount is applicable
        if product.discount:
            discounted_price = product.price - (product.price * product.discount / 100)
            product.discounted_price = discounted_price

    return render(request, 'giftweb/products.html', {'products': products})


@login_required
def make_payment(request, model_name, product_id):
    if model_name == 'product':
        model = Product
    elif model_name == 'premium_product':
        model = PremiumProduct
    else:
        return HttpResponseBadRequest("Invalid model name.")

    product = get_object_or_404(model, id=product_id)

    if request.method == 'POST':
        form = PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            payment = form.save(commit=False)
            payment.user = request.user
            payment.product = product  # Assign the product to the payment
            payment.status = 'PENDING'

            # Set the payment amount to the product price
            payment.amount = product.price

            payment.save()
            return redirect('giftweb:payment_success')
    else:
        form = PaymentForm()
    
    return render(request, 'giftweb/checkout.html', {'form': form, 'product': product})


@login_required
def payment_success(request):
    payment = Payment.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'giftweb/payment_success.html', {'payment': payment})

def about(request):
    return render(request, 'giftweb/about.html')


def blog_list(request):
    blogs = Blog.objects.all()
    return render(request, 'giftweb/blog.html', {'blogs': blogs})


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        subject = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
        user_id = request.POST['user_id']
        
        contact = Contactor(name=name, subject=subject, email=email, message=message, user_id=user_id)
        contact.save()

        messages.success(request, 'Your request has been submitted. We will get back to you soon!')
        
        return render(request, 'giftweb/contact.html')

    return render(request, 'giftweb/contact.html')




@login_required
def cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    return render(request, 'giftweb/cart.html', {'cart_items': cart_items})

@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    # Check if the product is already in the user's cart
    cart_item = CartItem.objects.filter(user=request.user, product=product).first()

    if cart_item:
        # Product already exists in the cart, update the quantity
        cart_item.quantity += 1
        cart_item.save()
    else:
        # Product does not exist in the cart, create a new cart item
        cart_item = CartItem(user=request.user, product=product, quantity=1)
        cart_item.save()

    return redirect('giftweb:cart')

class PremiumProductDetailView(DetailView):
    model = PremiumProduct
    template_name = 'giftweb/premiumproduct_detail.html'
    context_object_name = 'premium_product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        premium_product = self.get_object()

        # Add any additional context data for premium products here

        return context


@login_required
def payment_history(request):
    payments = Payment.objects.filter(user=request.user).order_by('-id')

    # Apply pagination with 7 entries per page
    paginator = Paginator(payments, 7)
    page_number = request.GET.get('page')  # Get the current page number from the request (e.g., query string parameter)

    # Get the corresponding page from the paginator
    page_obj = paginator.get_page(page_number)

    return render(request, 'giftweb/payment_history.html', {'page_obj': page_obj})

giftweb/templates/giftweb/base.html
{% load static %}
{% include "giftweb/messages.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORA - GiftCards &amp; Amazon | Home</title>
    <meta name="description" conten="ORA - Watches &amp; Jewelry">
    <meta name="author" content="Author Name">
    <meta name="keywords" content="Or&euml; Dore, Syze, Bizhuteri, Aksesore, Outlet etc..." />
    <link rel="icon" href="{% static 'assetso\img\favicon.png' %}" sizes="32x32" />
    <link rel="icon" href="{% static 'assetso\img\favicon.png' %}" sizes="192x192" />
    <link rel="apple-touch-icon" href="{% static 'assetso\img\favicon.png' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assetso\css\style.css' %}">
</head>
<style>
    @media (max-width: 767px) {  /* Hide the contact section in mobile view */
        #contact-section {
            display: none;
        }
    }
</style>

<body>

    <div class="page-loader loader">
        <div class="cmps">
            <span class="mt-4 mx-auto d-block text-center">
                Loading<b></b><b></b><b></b>
            </span>
        </div>
    </div>

    <header class="header">
        <div class="container">
            <section class="header--main">
                <div class="mobile-menu">
                    <input id="menu__toggle" class="open-nav" type="checkbox" />
                    <label class="menu__btn" class="open" for="menu__toggle">
                        <span></span>
                    </label>
                </div>
                <div class="header--logo">
                    <!-- <a href="./"><span>Ora</span> Watches &amp Jewelery</a> -->
                    <a href="./">
                        <img src="{% static 'assetso\img\light-logo.png' %}" style="max-width: 70px" alt="Ora Watches &amp; Jewelery | Logo">
                    </a>
                </div>
                <nav class="menu js-menu">
                    <ul class="ul-menu">
                        <li class="menu-item">
                            <a href="{% url 'giftweb:home' %}" class="active"style="font-size: 22px;">Home</a>
                        </li>

                        <li class="menu-item menu-item-child">
                            <a href="#" class="js-sub_menu"style="font-size: 22px;">Pages <i class="uil uil-angle-down"></i></a>
                            <ul class="sub-menu">
                                <li class="sub-menu-item"><a href="{% url 'accounts:login' %}">Log In</a></li>
                                <li class="sub-menu-item"><a href="{% url 'accounts:register' %}">Sign Up</a></li>
                                <li class="sub-menu-item"><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                                <li class="sub-menu-item"><a href="{% url 'giftweb:blog_list' %}">Blog</a></li>
                                <li class="sub-menu-item"><a href="{% url 'giftweb:payment_history' %}" style="font-size: 22px;">Payment History</a></li>
                            </ul>
                        </li>

                        <li class="menu-item">
                            <a href="{% url 'giftweb:premium_home' %}"style="font-size: 22px;">PREMIUM</a>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'giftweb:about' %}">About Us</a>
                        </li>

                        <li class="menu-item">
                            <a href="{% url 'giftweb:contact' %}">Contact Us</a>
                        </li>
                    </ul>
                </nav>
                <div class="darkLight-searchBox">
                    <div class="dark-light">
                        <!-- <i class="fa-solid fa-moon moon"></i> -->
                        <!-- <i class="fa-solid fa-sun"></i> -->
                        <i class="uil uil-moon moon"></i>
                        <i class="uil uil-sun sun"></i>
                    </div>
                    <div class="searchBox">
                        <div class="searchToggle">
                            <!-- <i class="fa-solid fa-xmark cancel"></i> -->
                            <!-- <i class="fa-solid fa-magnifying-glass search"></i> -->
                            <i class="uil uil-times cancel"></i>
                            <i class="uil uil-search search"></i>
                        </div>

                        <div class="search-field">
                            <input type="text" placeholder="Search..." />
                            <!-- <i class="fa-solid fa-magnifying-glass"></i> -->
                            <i class="uil uil-search-alt"></i>
                        </div>
                    </div>
<div class="cart-checkout" style="pointer-events: none;">
    <i class="uil uil-shopping-bag shopping-cart"></i>
</div>

                    <!-- <i class="fa-solid fa-bars open-nav"></i> -->
                </div>
                <small>{{ user.username }}</small>
            </section>
            <div class="progress"></div>
        </div>
    </header><!-- header-end ./ -->


    <main>
        {% block content %}
        {% endblock %}
    </main>

    {% block include_footer %}
        {% if not is_payment_history_page %}
            {% include 'accounts/footer.html' %}
        {% endif %}
    {% endblock %}<!-- footer-end ./ -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'assetso\js/script.js' %}"></script>
</body>
</html>

giftweb/templates/giftweb/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make_Payment - Gift_Card | {% block title %} {% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
<style>
    /* Add the following styles */
    body.dark-mode h1#card-title,
    body.dark-mode label.light-mode,
    body.dark-mode label#file-label,
    body.dark-mode label#selected-file-label {
        color: black !important;
    }
</style>


    <style>
        .gift-card-container {
            border: 2px solid black;
            padding: 20px;
            margin-bottom: 20px;
            background-color: #f9f9f9;
            color: #333333;
        }

        .dark-mode .gift-card-container {
            background-color: #333333;
            color: #ffffff;
        }

        .form-container {
            padding-bottom: 80px; /* Adjust the padding bottom value as needed */
        }
    </style>
    <style>
        body {
            transition: background-color 0.3s, color 0.3s;
        }

        .light-mode {
            background-color: #ffffff;
            color: #000000;
        }

        .dark-mode {
            background-color: #222222;
            color: #ffffff;
        }

        .gift-card-container {
            background-color: #f9f9f9;
            color: #333333;
        }

        .dark-mode .gift-card-container {
            background-color: #333333;
            color: #ffffff;
        }

    </style>
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            transition: .4s;
            border-radius: 34px;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            transition: .4s;
            border-radius: 50%;
        }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:checked + .slider:before {
            transform: translateX(26px);
        }

        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 id="card-title" class="card-title text-center">Complete Transaction using Gift Card</h1>
                    <p id="card-subtitle" class="text-muted text-center">To proceed, kindly make a selection from the available gift card types: Apple Card, Amazon Card, Steam Card, or Xbox Card.</p>
                    <div id="gift-card-section" class="text-center">
                        <div class="gift-card-container">
                            <img id="gift-card-img-top" src="https://cdn.redmondpie.com/wp-content/uploads/2011/07/Apple-Logo.png" alt="Apple Card" width="100" height="100">
                            <h4 id="gift-card-name">Apple Card</h4>
                        </div>
                    </div>
                    <div class="form-container"> <!-- Added container for form section -->
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label id="file-label" for="{{ form.amount.id_for_label }}">Transaction Value:</label>
                                <input id="amount-input" type="text" class="form-control" value="{{ product.price }}" readonly name="amount">
                            </div>
                        <div class="form-group">
                            <label id="file-label" for="{{ form.proof_of_pay.id_for_label }}">Proof of Payment:</label>
                            {{ form.proof_of_pay }}
                            <label id="selected-file-label" for="{{ form.proof_of_pay.id_for_label }}">No document selected</label>
                        </div>
                            <div class="form-group">
                                <label id="file-label" for="id_gift_card_type">Select Gift Card Type:</label>
                                <div class="input-group">
                                    <div class="gift-card-list-container">
                                        <select id="id_gift_card_type" name="gift_card_type" class="form-control">
                                            <option value="apple">Apple Card</option>
                                            <option value="amazon">Amazon Card</option>
                                            <option value="steam">Steam Card</option>
                                            <option value="xbox">Xbox Card</option>
                                        </select>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <img id="gift-card-img" src="https://cdn.redmondpie.com/wp-content/uploads/2011/07/Apple-Logo.png" alt="Apple Card" width="30" height="30">
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



    <div class="text-center mb-4">
        <label class="switch">
            <input type="checkbox" id="toggle-theme">
            <span class="slider round"></span>
        </label>
        <span id="theme-label">Light Mode</span>
    </div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
<script>
    const fileInput = document.getElementById('id_proof_of_pay');
    const fileLabel = document.getElementById('selected-file-label');

    fileInput.addEventListener('change', function() {
        if (fileInput.files.length > 0) {
            fileLabel.textContent = fileInput.files[0].name;
        } else {
            fileLabel.textContent = 'No document selected';
        }
    });
</script>

    <script>
        const selectElement = document.getElementById('id_gift_card_type');
        const giftCardImgTop = document.getElementById('gift-card-img-top');
        const giftCardName = document.getElementById('gift-card-name');
        const giftCardImg = document.getElementById('gift-card-img');
        const toggleTheme = document.getElementById('toggle-theme');
        const themeLabel = document.getElementById('theme-label');

        selectElement.addEventListener('change', (event) => {
            if (event.target.value === 'apple') {
                giftCardImgTop.src = 'https://cdn.redmondpie.com/wp-content/uploads/2011/07/Apple-Logo.png';
                giftCardImgTop.alt = 'Apple Card';
                giftCardName.innerText = 'Apple Card';
                giftCardImg.src = 'https://cdn.redmondpie.com/wp-content/uploads/2011/07/Apple-Logo.png';
                giftCardImg.alt = 'Apple Card';
            } else if (event.target.value === 'amazon') {
                giftCardImgTop.src = 'https://www.citypng.com/public/uploads/preview/-11596312183geendnnbmv.png';
                giftCardImgTop.alt = 'Amazon Card';
                giftCardName.innerText = 'Amazon Card';
                giftCardImg.src = 'https://www.citypng.com/public/uploads/preview/-11596312183geendnnbmv.png';
                giftCardImg.alt = 'Amazon Card';
            } else if (event.target.value === 'steam') {
                giftCardImgTop.src = 'https://cdn.wallpapersafari.com/58/91/rXpM7m.png';
                giftCardImgTop.alt = 'Steam Card';
                giftCardName.innerText = 'Steam Card';
                giftCardImg.src = 'https://cdn.wallpapersafari.com/58/91/rXpM7m.png';
                giftCardImg.alt = 'Steam Card';
            } else if (event.target.value === 'xbox') {
                giftCardImgTop.src = 'https://i.pinimg.com/originals/e0/be/50/e0be5066ace675eb18bb130d95be81b9.png';
                giftCardImgTop.alt = 'Xbox Card';
                giftCardName.innerText = 'Xbox Card';
                giftCardImg.src = 'https://i.pinimg.com/originals/e0/be/50/e0be5066ace675eb18bb130d95be81b9.png';
                giftCardImg.alt = 'Xbox Card';
            }
        });

        toggleTheme.addEventListener('change', (event) => {
            if (event.target.checked) {
                document.body.classList.add('dark-mode');
                themeLabel.innerText = 'Dark Mode';
            } else {
                document.body.classList.remove('dark-mode');
                themeLabel.innerText = 'Light Mode';
            }
        });
    </script>
</body>
</html>

giftweb/templates/giftweb/indexold.html
{% extends 'giftweb/base.html' %}

{% block title %}
    GiftWeb - Home
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Welcome to GiftWeb</h1>
        <h2>Available Products:</h2>
        <div class="product-list">
            {% for product in products %}
                <div class="product-item">
                    <h3 class="product-name"><a href="{% url 'giftweb:product_detail' product.id %}">{{ product.name }}</a></h3>
                    <p class="remaining-time">Remaining Time: {{ product.remaining_days }} days, {{ product.remaining_hours }} hours, {{ product.remaining_minutes }} minutes, {{ product.remaining_seconds }} seconds</p>
                    <!-- Other product details -->
                </div>
            {% empty %}
                <p>No products available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}